stages:
  - test
  - build
  - push-image
  - deploy

test:
  stage: test
  image: node:18.16-alpine
  before_script:
    - npm install
  script:
    - npm run test

build:
  stage: build
  image: node:18.16-alpine
  before_script:
    - npm install
  script:
    - npm run build

push-image:
  stage: push-image
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
  script:
    - docker build -t folt3k/gitlab-ci-test-app .
    - docker push folt3k/gitlab-ci-test-app

deploy:
  stage: deploy
  before_script:
    - chmod 400 $DEPLOY_SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $DEPLOY_SSH_KEY ubuntu@54.37.73.239 "
      docker login -u $DOCKER_USER -p $DOCKER_PASS &&
      docker ps -aq | xargs docker stop | xargs docker rm &&
      docker run -d -p 8000:8000 folt3k/gitlab-ci-test-app:latest"
