stages:
  - test
  - build
  - push-image

test:
  stage: test
  image: node:18.16-alpine
  before_script:
    - npm install
  script:
    - npm run test

build:
  stage: build
  image: node:18.16-alpine
  before_script:
    - npm install
  script:
    - npm run build

push-image:
  stage: push-image
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
  script:
    - docker build -t folt3k/gitlab-ci-test-app .
    - docker push folt3k/gitlab-ci-test-app
