run_tests:
  image: node:18.16-alpine
  before_script:
    - npm install
  script:
    - npm run test

build-image:
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
  script:
    - docker build -t folt3k/gitlab-ci-test-app .
    - docker push folt3k/gitlab-ci-test-app
